### ISSUE TITLE
[docs] No docs for `serialize()`, which is listed as a namespace

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/vastly#14]
https://vastly.mavo.io/docs/modules/serialize.html

It appears that `serialize()` becoming a namespace means it loses all the docs about itself. That appears to be a bug in typedoc.

Tasks:
- [ ] Investigate if there is a workaround (e.g. some way to explicitly specify that this is a function)
- [ ] Investigate whether the bug is already reported and report it if not https://github.com/TypeStrong/typedoc/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
	- Make sure you include a minimal testcase that reproduces the issue

**Comment by LeaVerou** [comment]
Given this now affects 3 of our functions: https://vastly.mavo.io/docs/ I'm bumping its priority to Medium.

**Comment by LeaVerou** [comment]
Yay, this is fixed in the latest Typedoc version!!

**Comment by adamjanicki2** [comment]
Awesome!! Was planning on trying to address this today; glad to see they fixed it!
